name: al_quran
description: Flutter App for the holy book of Qur'an.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  shimmer: ^1.1.1  
  shared_preferences: ^0.5.7+3
  share: ^0.6.4+3
  url_launcher: ^5.4.11
  launch_review: ^2.0.0
  
  flutter_overboard: ^1.1.5
  flutter_svg: ^0.18.0

dependency_overrides:
  image:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  fonts:
    - family: Sogeo
      fonts:
        - asset: fonts/sui.ttf
    #     - asset: fonts/Raleway-Italic.ttf
    #       style: italic
    - family: ShareIcon
      fonts:
        - asset: fonts/ShareIcon.ttf
  